services:
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
  redis:
    image: redis:7.4.1
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
  redis: